### ISSUE TITLE
Implement Remote Signer gRPC Server

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/remote-signer#1]
This is a tracking issue for implementing a gRPC server for the following protobuf service definition: [prysm remote keymanager v2 PR](https://github.com/prysmaticlabs/prysm/blob/95dd63a664ed2f670652ec84de20f7e5168c8dd5/proto/validator/accounts/v2/keymanager.proto). Namely, the server needs to implement two main RPC methods: `ListAccounts` and `Sign`. Aside from that, it can choose to store its secrets however it wants, with possible integration of a third party such as [Hashicorp Vault](https://learn.hashicorp.com/vault). This server should only accept secure gRPC connections.

- [x] Create the gRPC server with secure options
- [x] Implement account generation
- [x] Decide how to store secrets: (possibly simple direct keystores for now, with hashicorp integration in the future)
- [x] Implement the sign method
- [x] Add comprehensive README
- [ ] Keep track of data that was previously signed to prevent slashable conditions (can be naively implemented for now)
- [ ] Add gRPC gateway support

This implementation is meant to be a reference approach, and not likely something used extensively in production. Notwithstanding, it should have sufficient tests and top-notch documentation for anyone building a remote signer for Prysm.

**Comment by terencechain** [comment]
Working on ` Create the gRPC server with secure options`
